version: '3'
services:

  configservice:
    image: lunchplan/configservice
    ports:
    - 50000:50000

  logspout:
    image: gliderlabs/logspout:v3
    command: 'syslog://logstash:5000'
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'

  logstash:
    image: logstash:5.6.8
    command: 'logstash -e "input { udp { port => 5000 } } output { elasticsearch { hosts => elasticsearch } }"'
    ports:
    - '5000:5000'

  kibana:
    image: kibana
    environment:
    - LOGSPOUT=ignore
    ports:
    - '5601:5601'

  elasticsearch:
    image: elasticsearch
    environment:
    - LOGSPOUT=ignore

  mongodb:
    image: lunchplan/mongo-seed
    ports:
    - "27017:27017"
    environment:
    - LOGSPOUT=ignore

  portainer:
    image: portainer/portainer
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 9000:9000
    deploy:
      placement:
        constraints: [node.role == manager]
    # Setting admin password to 'admin'
    command: --admin-password '$$2y$$05$$7/1USzltvCnkJQTSmOtj8.pXnExAOv4yY.fAiFza2VT7kxptSDk5m'

  apiservice:
    image: lunchplan/apiservice
    ports:
    - 50001:50001

  htmlservice:
    image: lunchplan/htmlservice
    ports:
    - 50002:50002

  userservice:
    image: lunchplan/userservice
    ports:
    - 50003:50003

  mealservice:
    image: lunchplan/mealservice
    ports:
    - 50004:50004
    deploy:
      replicas: 3

  tagservice:
    image: lunchplan/tagservice
    ports:
    - 50005:50005

  calendarservice:
    image: lunchplan/calendarservice
    ports:
    - 50006:50006

  apigateway:
    image: lunchplan/apigateway
    ports:
    - 80:80
    - 4430:4430

  viz:
    image: dockersamples/visualizer
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
    - 9090:8080