GET http://localhost:50000/

<> 2018-04-04T092752.200.json

### Registracija
POST http://localhost/api/register
Content-Type: application/json

{
  "email": "value50",
  "password": "value2",
  "firstname": "Karlo",
  "lastname": "Šimunović"
}

<> 2018-04-04T093631.200.json
<> 2018-04-04T093624.200.txt

### Login
POST http://localhost/api/login
Content-Type: application/json

{
  "email": "value50",
  "password": "value2"
}
> {% client.global.set("auth_token", response.body.Data.pid); %}

### Dohvaćanje accounta s JWT tokenom
GET http://localhost/api/account
Authorization: Bearer {{auth_token}}

<> 2018-04-04T093743.200.json

### Dohvaćanje blogova s JWT tokenom
POST http://localhost/api/blog
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "title":"Naslov",
    "content":"Nekakav dugački tekst"
}

<> 2018-04-04T093859.200.json


### Dohvaćanje blogova s JWT tokenom
GET http://localhost/api/blogs
Authorization: Bearer {{auth_token}}

<> 2018-04-04T093904.200.json
<> 2018-04-04T093722.200.json
###
