GET http://docker:50000/

> {% client.global.set("port", 4430); %}

### Registracija prvog usera
POST https://localhost:{{port}}/api/register
Content-Type: application/json

{
  "email": "probniEmail",
  "password": "dugackaSigurnaSifra",
  "firstname": "Karlo",
  "lastname": "Šimunović"
}


### Registracija drugog usera
POST https://localhost:{{port}}/api/register
Content-Type: application/json

{
  "email": "peroslav@gmail.com",
  "password": "dugackaSigurnaSifra",
  "firstname": "Pero",
  "lastname": "Slav"
}

### Login Karlo
POST https://localhost:{{port}}/api/login
Content-Type: application/json

{
  "email": "probniEmail",
  "password": "dugackaSigurnaSifra"
}
> {% client.global.set("auth_token", response.body.sid); %}

### Login Peroslav
POST https://docker:{{port}}/api/login
Content-Type: application/json

{
  "email": "peroslav@gmail.com",
  "password": "dugackaSigurnaSifra"
}
> {% client.global.set("auth_token", response.body.sid); %}

### Dohvaćanje info o  accountu s JWT tokenom
GET https://localhost:{{port}}/api/account
Authorization: Bearer {{auth_token}}

### --------MEAL SERVICE


### Create - Unos meal-a
POST https://localhost:{{port}}/api/meal
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "title":"Naslov",
    "description":"Nekakav dugački tekst",
    "tags": [{
         "name": "hey hey"
     }]
}
> {% client.global.set("meal1", response.body.id); %}

### GetAllUserMeals - Dohvaćanje svih meal-ova ulogiranog korisnika
GET https://localhost:{{port}}/api/meal/all
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Suggest - Dohvaćanje radnom meal-a
GET https://localhost:{{port}}/api/meal/suggest
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Read - Dohvaćanje meal-a prema id-u
GET https://localhost:{{port}}/api/meal/{{meal1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Update - Ažuriranje meal-a
POST https://localhost:{{port}}/api/meal/{{meal1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
"id": "5ade281d239c97ba4400e6cc2",
    "title":"WHAaat?2",
    "description":"Izmjenjeni content meal-a"
}

### Delete - Brisanje meal-a
DELETE https://localhost:{{port}}/api/meal/{{meal1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

### Create - Unos tag-a
POST https://localhost:{{port}}/api/tag
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "name":"naslov taga"
}

> {% client.global.set("tag1", response.body.id); %}

### GetAllUSerTags - Dohvaćanje svih tag-ova ulogiranog korisnika
GET https://localhost:{{port}}/api/tag/all
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {% client.global.set("tag1", response.body[0].id); %}

### Read - Dohvaćanje tag-a prema id-u
GET https://localhost:{{port}}/api/tag/{{tag1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Update - Ažuriranje tag-a
POST https://localhost:{{port}}/api/tag/{{tag1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "name":"AžuriranoIme2"
}

### Delete - Brisanje meal-a
DELETE https://localhost:{{port}}/api/tag/{{tag1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

### Create - Unos calendara-a
POST https://localhost:{{port}}/api/calendar
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "date":"2018-04-28",
    "meal_id":"5ae4b3323cd05032c8153057"
}

> {% client.global.set("calendar1", response.body.id); %}

### GetAllUserCalendars - Dohvaćanje svih calendar-a ulogiranog korisnika
GET https://localhost:{{port}}/api/calendar/all
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {% client.global.set("calendar1", response.body[0].id); %}

### Read - Dohvaćanje calendar-a prema id-u
GET https://localhost:{{port}}/api/calendar/{{calendar1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}


### Update - Ažuriranje calendar-a
POST https://localhost:{{port}}/api/calendar/{{calendar1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "date":"2018-05-25"
}


### Delete - Brisanje calendar-a
DELETE https://localhost:{{port}}/api/calendar/{{calendar1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}


###
#################################################################################
GET http://192.168.99.101:50000/

> {% client.global.set("port", 4430); %}

### Registracija prvog usera
POST https://192.168.99.101:{{port}}/api/register
Content-Type: application/json

{
  "email": "probniEmail",
  "password": "dugackaSigurnaSifra",
  "firstname": "Karlo",
  "lastname": "Šimunović"
}


### Registracija drugog usera
POST https://192.168.99.101:{{port}}/api/register
Content-Type: application/json

{
  "email": "peroslav@gmail.com",
  "password": "dugackaSigurnaSifra",
  "firstname": "Pero",
  "lastname": "Slav"
}

### Login Karlo
POST https://192.168.99.101:{{port}}/api/login
Content-Type: application/json

{
  "email": "probniEmail",
  "password": "dugackaSigurnaSifra"
}
> {% client.global.set("auth_token", response.body.sid); %}

### Login Peroslav
POST https://localhost:4430/api/login
Content-Type: application/json

{
  "email": "peroslav@gmail.com",
  "password": "dugackaSigurnaSifra"
}
> {% client.global.set("auth_token", response.body.sid); %}

### Dohvaćanje info o  accountu s JWT tokenom
GET https://localhost:{{port}}/api/account
Authorization: Bearer {{auth_token}}

### --------MEAL SERVICE


### Create - Unos meal-a
POST https://localhost:{{port}}/api/meal
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "title":"Naslov",
    "description":"Nekakav dugački tekst",
    "tags": [{
         "name": "hey hey"
     }]
}
> {% client.global.set("meal1", response.body.id); %}

### GetAllUserMeals - Dohvaćanje svih meal-ova ulogiranog korisnika
GET https://localhost:{{port}}/api/meal/all
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Suggest - Dohvaćanje radnom meal-a
GET https://localhost:{{port}}/api/meal/suggest
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Read - Dohvaćanje meal-a prema id-u
GET https://localhost:{{port}}/api/meal/{{meal1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Update - Ažuriranje meal-a
POST https://localhost:{{port}}/api/meal/{{meal1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
"id": "5ade281d239c97ba4400e6cc2",
    "title":"WHAaat?2",
    "description":"Izmjenjeni content meal-a"
}

### Delete - Brisanje meal-a
DELETE https://localhost:{{port}}/api/meal/{{meal1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

### Create - Unos tag-a
POST https://localhost:{{port}}/api/tag
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "name":"naslov taga"
}

> {% client.global.set("tag1", response.body.id); %}

### GetAllUSerTags - Dohvaćanje svih tag-ova ulogiranog korisnika
GET https://localhost:{{port}}/api/tag/all
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {% client.global.set("tag1", response.body[0].id); %}

### Read - Dohvaćanje tag-a prema id-u
GET https://localhost:{{port}}/api/tag/{{tag1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Update - Ažuriranje tag-a
POST https://localhost:{{port}}/api/tag/{{tag1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "name":"AžuriranoIme2"
}

### Delete - Brisanje meal-a
DELETE https://localhost:{{port}}/api/tag/{{tag1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

### Create - Unos calendara-a
POST https://localhost:{{port}}/api/calendar
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "date":"2018-04-28",
    "meal_id":"5ae4b3323cd05032c8153057"
}

> {% client.global.set("calendar1", response.body.id); %}

### GetAllUserCalendars - Dohvaćanje svih calendar-a ulogiranog korisnika
GET https://localhost:{{port}}/api/calendar/all
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {% client.global.set("calendar1", response.body[0].id); %}

### Read - Dohvaćanje calendar-a prema id-u
GET https://localhost:{{port}}/api/calendar/{{calendar1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}


### Update - Ažuriranje calendar-a
POST https://localhost:{{port}}/api/calendar/{{calendar1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "date":"2018-05-25"
}


### Delete - Brisanje calendar-a
DELETE https://localhost:{{port}}/api/calendar/{{calendar1}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}


###